<a href="https://colab.research.google.com/github/enidroman/Math-With-Python/blob/main/MATH_HW_2_Enid_Roman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Do not use built in programs to do the following.  Write the programs to demonstrate that you understand the math behind them.  Provide all solutions in an .html file. 

# 1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [6]:
# importing numpy library
import numpy as np

In [7]:
# create numpy 2d-array
m = np.mat("3 4;4 6")
print("Printing the Original square array:\n", m)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n", w)

# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n", v)

Printing the Original square array:
 [[3 4]
 [4 6]]
Printing the Eigen values of the given square array:
 [0.22799813 8.77200187]
Printing Right eigenvectors of the given square array:
 [[-0.82192562 -0.56959484]
 [ 0.56959484 -0.82192562]]


# 2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition.

### The SVD can be calculated by calling the svd() function.

### The function takes a matrix and returns the U, Sigma and V^T elements. The Sigma diagonal matrix is returned as a vector of singular values. The V matrix is returned in a transposed form, e.g. V.T.

### Running the example first prints the defined 2×2 matrix, then the 2×2 U matrix, 1 element Sigma vector, and 2×2 V^T matrix elements calculated from the decomposition.



In [8]:
# create a numpy array
arr = np.array([[10, 2], [0, 7]], dtype=np.float32)
print("Original array:")
print(arr)
  
# compute the factor 
U, s, V = np.linalg.svd(arr, full_matrices=False)
  
# print the result
print("\nFactor of the given array  by Singular Value Decomposition:")
print("\nU=", U, "\n\ns=", s, "\n\nV=", V)

Original array:
[[10.  2.]
 [ 0.  7.]]

Factor of the given array  by Singular Value Decomposition:

U= [[ 0.9724102 -0.2332776]
 [ 0.2332776  0.9724102]] 

s= [10.361397   6.7558455] 

V= [[ 0.9384933   0.34529743]
 [-0.34529743  0.9384933 ]]


# 3.  Write a Python program to compute the determinant of an array.

### Determinant for a matrix [[a,b], [c,d]], the determinant is is calculated as ‘ad-bc’. The larger square matrices are considered to be a combination of 2x2 matrices.

In [9]:
from numpy import linalg
  
# creating a 2X2 matrix
matrix = np.array([[5, 6], [7, 8]])
print("Original 2-D matrix")
print(matrix)
  
# print the result
print("Determinant of the 2-D matrix:")
print(np.linalg.det(matrix))

Original 2-D matrix
[[5 6]
 [7 8]]
Determinant of the 2-D matrix:
-2.000000000000005
